import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from "@clerk/themes";
import Footer from "@/components/footer";
import LoadingScreen from "@/components/LoadingScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Talensia-AI Career Analyzer",
  description: "Generated by Talensia-AI",
  icons: {
    icon: [{ url: "/logo22.png" }],
    shortcut: [{ url: "/logo22.png" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/logo22.png" sizes="any" />
        </head>
        <body className={`${inter.className} relative`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Global Loading Splash (2 seconds) */}
            <LoadingScreen />

            {/* Main site content */}
            <div className="relative z-10">
              <Header />
              <main className="min-h-screen">{children}</main>
              <Footer />
            </div>

            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
